# This workflow is responsible for building the standard library using the bootstrap script
# and executing the Rust regression.

name: Rust Tests
on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches: [ main ]
  push:
    paths:
      - 'library/**'
      - 'rust-toolchain.toml'
      - '.github/workflows/rustc.yml'
      - 'scripts/check_rustc.sh'

defaults:
  run:
    shell: bash

jobs:
  upstream_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Note windows-latest is currently failing.
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout Library
        uses: actions/checkout@v4

      - name: Run rustc script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/check_rustc.sh
